apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: bigqueryreservationassignments.bigqueryreservation.cnrm.cloud.google.com
spec:
  group: bigqueryreservation.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: BigQueryReservationAssignment
    listKind: BigQueryReservationAssignmentList
    plural: bigqueryreservationassignments
    shortNames:
    - gcpbigqueryreservationassignment
    - gcpbigqueryreservationassignments
    singular: bigqueryreservationassignment
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BigQueryReservationAssignment is the Schema for the BigQueryReservationAssignment
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BigQueryReservationAssignmentSpec defines the desired state
              of BigQueryReservationAssignment
            properties:
              assignee:
                description: Immutable. The resource which will use the reservation.
                  E.g. `projects/myproject`, `folders/123`, or `organizations/456`.
                type: string
                x-kubernetes-validations:
                - message: assignee field is immutable
                  rule: self == oldSelf
              jobType:
                description: Immutable. Which type of jobs will use the reservation.
                type: string
                x-kubernetes-validations:
                - message: jobType field is immutable
                  rule: self == oldSelf
              location:
                description: Can be changed when moving the assignment from one reservation
                  to another reservation.
                type: string
              projectRef:
                description: The Project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              reservationName:
                description: Can be changed when moving the assignment from one reservation
                  to another reservation.
                type: string
              resourceID:
                description: 'Immutable. Optional. The BigQueryReservationAssignment
                  ID used for resource creation or acquisition. Service-generated,
                  can only be specified for resource acquisition. For acquisition:
                  This field must be provided to identify the Reservation resource
                  to acquire.'
                type: string
            required:
            - assignee
            - jobType
            - location
            - projectRef
            - reservationName
            type: object
          status:
            description: BigQueryReservationAssignmentStatus defines the config connector
              machine state of BigQueryReservationAssignment
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the BigqueryReservationAssignment
                  resource in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  name:
                    description: 'Name of the resource. E.g.: `projects/myproject/locations/US/reservations/team1-prod/assignments/123`.
                      The assignment_id must only contain lower case alphanumeric
                      characters or dashes and the max length is 64 characters.'
                    type: string
                  state:
                    description: State of the assignment.
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
